// TRANSPARENT
#define PARALLAX_TRANSPARENT_STEPS 4

#define PARALLAX_TRANSPARENT_HEIGHT_WATER         1.1
#define PARALLAX_TRANSPARENT_HEIGHT_ICE           0.7
#define PARALLAX_TRANSPARENT_HEIGHT_STAINED_GLASS 0.2
